"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["div[_ngcontent-%COMP%] {\n  h1 {\n    color: green;\n  }\n}"];
exports.styles = styles;
//# sourceMappingURL=products.component.scss.shim.ngstyle.js.map